[build]
  base = "client/"
  command = "npm install && npm run build"
  publish = "dist/"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://pastebin-lite-backend.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/p/*"
  to = "https://pastebin-lite-backend.onrender.com/p/:splat"
  status = 200

[[redirects]]
  from "/*"
  to = "/index.html"
  status = 200
